
// Stored modelname (without quotes): "h:\SDK2\SDK\Weapon~1\ns\p_models\p_sg.mdl"
$modelname "p_sg.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "p_sg_ref"
}

$flags 0


$attachment 0 "Bip01 R Hand" 23.700001 -1.1 6.6


$hbox 0 "Bip01 Neck" -2.869902 0 -4.140396 0 1.399666 0
$hbox 0 "Bip01 R Hand" -4.54 -2.09 -1.04 23.389999 2.37 7.93

$sequence "idle" {
	"p_sg_anims\idle"
	fps 30
}
