
// Stored modelname (without quotes): "D:\SDK2\SDK\Weapon Models\NS\resource_nozzle\resource_nozzle.mdl"
$modelname "b_resource_nozzle.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "nozzle_reference"
}

$flags 0

$externaltextures


$attachment 0 "Dummy01" 0 4 0

$hbox 0 "Dummy01" -41.529999 0 -37.41 37.400002 11.51 37.369999

$sequence "idle" {
	"b_resource_nozzle_anims\idle"
	fps 5
	loop
}
