sprites/minimaps/ns_ragnarok.spr
sprites/minimaps/ns_ragnarok_1.spr
sprites/minimaps/ns_ragnarok_2.spr
sprites/minimaps/ns_ragnarok_3.spr
sprites/minimaps/ns_ragnarok_4.spr
sprites/minimaps/ns_ragnarok_5.spr
models/ns_ragnarok/fern.mdl
sound/ns_ragnarok/animelol.mp3
sound/ns_ragnarok/ysaye_clip.mp3