
// Stored modelname (without quotes): "h:\SDK2\SDK\Weapon~1\ns\p_models\p_pistol.mdl"
$modelname "p_hg.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "p_pistol_ref"
}

$flags 0


$attachment 0 "Bip01 R Hand" 13 1 4


$hbox 0 "Bip01 Neck" -2.869898 0 -4.140396 0 1.399663 0
$hbox 0 "Bip01 R Hand" 0 -0.01 -2.53 12.26 1.81 4.79

$sequence "idle" {
	"p_hg_anims\idle"
	fps 30
}
