
// Stored modelname (without quotes): "C:\3dmax31\Scenes\natural_selection\p_w_weapons\p_gg.mdl"
$modelname "p_gg.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "body"
{
	studio "p_gg_ref"
}

$flags 0


$attachment 0 "Bip01 R Hand" 17.700001 1.9 8.6


$hbox 0 "Bip01 R Hand" 0 -1.589536 0 11.24647 0 6.229363
$hbox 0 "p_gl_tex" -7.76 0 -13.65 6.49 6.47 16.83

$sequence "idle" {
	"p_gg_anims\idle"
	fps 20
}
