
// Stored modelname (without quotes): "C:\3DMAX31\Scenes\natural_selection\marine\lmg\p_mg.mdl"
$modelname "p_mg.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "body"
{
	studio "p_lmg_ref"
}

$flags 0


$attachment 0 "Bip01 R Hand" 18 2 7


$hbox 0 "Bip01 R Hand" 0 0 0 5.205287 4.313621 2.913102
$hbox 0 "p_mg" -5.19 -11.43 -7.69 5.18 11.42 7.68

$sequence "idle" {
	"p_mg_anims\idle"
	fps 20
}
